
//----------------------------------------------------
// The following code was generated by jh-javacup-1.0 20160720
// Sun May 23 13:55:06 MST 2021
//----------------------------------------------------

package edu.utexas.cs.utopia.specLang.parse;

/** CUP generated class containing symbol constants. */
public class SpecLangSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int TRUE = 2;
  public static final int FALSE = 3;
  public static final int LPAR = 4;
  public static final int RPAR = 5;
  public static final int LOC = 6;
  public static final int CONSTRAINT_BEGIN = 7;
  public static final int CONSTRAINT_END = 8;
  public static final int ALWAYS = 9;
  public static final int EVENTUALLY = 10;
  public static final int UNTIL = 11;
  public static final int RELEASE = 12;
  public static final int AND = 13;
  public static final int OR = 14;
  public static final int IMPLIES = 15;
  public static final int NEXT = 16;
  public static final int NEG = 17;
  public static final int SEQ = 18;
  public static final int LBRACKET = 19;
  public static final int RBRACKET = 20;
  public static final int PLUS = 21;
  public static final int MINUS = 22;
  public static final int UMINUS = 23;
  public static final int MULTIPLY = 24;
  public static final int DIVIDE = 25;
  public static final int EQ = 26;
  public static final int NEQ = 27;
  public static final int GT = 28;
  public static final int GEQ = 29;
  public static final int LT = 30;
  public static final int LEQ = 31;
  public static final int CALL = 32;
  public static final int SUCCESS = 33;
  public static final int OUT_OF_GAS = 34;
  public static final int REVERT = 35;
  public static final int REQUIRE = 36;
  public static final int ASSERT = 37;
  public static final int FAILL = 38;
  public static final int ARG_SEP = 39;
  public static final int CALL_SUCCESS = 40;
  public static final int OLD = 41;
  public static final int SUM = 42;
  public static final int FSUM = 43;
  public static final int INV = 44;
  public static final int STARTED = 45;
  public static final int WILL_SUCCEED = 46;
  public static final int FINISHED = 47;
  public static final int REVERTED = 48;
  public static final int SENT = 49;
  public static final int NAME = 50;
  public static final int INT = 51;
}

